# Generated by Django 4.1.4 on 2022-12-24 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dockerfile", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("processing", "processing"),
                            ("fail", "fail"),
                            ("error", "error"),
                            ("init", "init"),
                        ],
                        default="init",
                        max_length=10,
                    ),
                ),
                ("performance", models.FloatField(null=True)),
            ],
        ),
    ]
